### ISSUE TITLE
Compare missing against TFS

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/VsShowMissing#1]
ChrisTorng writes in the VS Gallery:

"Can you compare project referenced files to TFS source control files, shows any files that exists in TFS source control, but not in project referenced files, and vice versa?"

**Comment by Mertsch** [comment]
@flcdrg I am not sure about this, as this feature is included within VS when using a local workspace

https://www.visualstudio.com/en-us/docs/tfvc/decide-between-using-local-server-workspace#local
> Visual Studio automatically detects changes. When you add or delete files outside of Visual Studio, the program automatically detects these changes.

**Comment by flcdrg** [comment]
Going to close this. If anyone wants to implement it, then feel free!
