### ISSUE TITLE
Option 'Message importance' not stored

### ISSUE THREAD

**Issue by wilhelmmedetz** [flcdrg/VsShowMissing#105]
- Initially when opening the options dialog 'message importance' is empty and the extension generates all messages at error level.
- After changing the message importance to 'Warning' messages are generated at warning level.
- When exiting Visual Studio and restarting it the selected message level is empty again and messages are generated at error level.

**Comment by ErikLevin** [comment]
I have the same problem, except for me, the messages are always generated as Errors no matter what I set in the dialog. Using the VS2019 extension.

**Comment by goran-w** [comment]
Same here.

**Comment by goran-w** [comment]
I looked at the OptionsDialogPage class in the source code. The bindings for "Message importance" (`TaskErrorCategory MessageLevel`) and "When to check for missing files" (`RunWhen Timing`) seem to be implemented very similarly, with the only difference being that the type of the former `enum TaskErrorCategory` resides in external assembly `Microsoft.VisualStudio.Shell`.

**Comment by MikeWilliams-UK** [comment]
I have the problem that the settings are not saved at all.

**Comment by MikeWilliams-UK** [comment]
It's so bad I have had to uninstall the extension.

**Comment by flcdrg** [comment]
Hi everyone. I think I've fixed this with the latest update. Please let me know how you go.
