### ISSUE TITLE
Define Category and Tool in Error List

### ISSUE THREAD

**Issue by jerone** [flcdrg/VsShowMissing#12]
In the Error List window could you define an `Category` and `Tool` so errors are linked to this addon.

![vsshowmissing](https://cloud.githubusercontent.com/assets/55841/16919931/e1830172-4d0b-11e6-9125-123c4f831b50.png)

In the screenshot above Web Accessibility Checker uses [those](https://github.com/madskristensen/WebAccessibilityChecker/blob/1fea7abc6aded863ca947a1a84f26699e64326ae/src/ErrorList/TableEntriesSnapshot.cs#L88) [properties](https://github.com/madskristensen/WebAccessibilityChecker/blob/1fea7abc6aded863ca947a1a84f26699e64326ae/src/ErrorList/TableEntriesSnapshot.cs#L46).

**Comment by flcdrg** [comment]
I did try and do that but couldn't figure out how. I'll check out Mads' code to see how he did it.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
