### ISSUE TITLE
Disable files that exist but are not included

### ISSUE THREAD

**Issue by blubberbo** [flcdrg/VsShowMissing#24]
So I understand that the plugin shows: 
1) files that are included in the solution but do not exist
2) files that exist but are not included in the solution

Is there a way where we can only do number 1? Meaning, I don't want to see errors for files that exist but are not included in the solution - I _only_ want to see files that are included in the solution but do not exist.

great work overall!

**Comment by flcdrg** [comment]
Yes, if you uncheck 'Detect non-include files' in Tools | Options | Show Missing, that will do what you want.

![image](https://cloud.githubusercontent.com/assets/384747/22909841/555a3fe4-f2a6-11e6-942a-626f505d98bb.png)

**Comment by blubberbo** [comment]
@flcdrg genius! thank you so much!
