### ISSUE TITLE
Missing Project Files Stop Other Projects From Compiling

### ISSUE THREAD

**Issue by squatched** [flcdrg/VsShowMissing#29]
I work with multiple apps that operate under the paradigm of one project generates code for another project. When coming into a clean solution, this extension keeps EVERY project from building. There is a specified dependency order (build Generator Project whose output is input to the next project) that with this extension enabled cannot be followed. When trying to build just the Generator Project (that is not missing any files), I am told that files from the next project are missing.

Until a project is actually compiled, it should not be scanned for missing files. If completely unrelated project A is missing files, it should not keep project B from ever compiling.

**Comment by flcdrg** [comment]
So you're saying the scanning should only occur before/after each project is compiled rather than doing the whole solution?

That sounds reasonable. I'll have to check whether there's an event I can leverage to do that.
