### ISSUE TITLE
Please add or support Visual Studio 2022

### ISSUE THREAD

**Issue by MikeWilliams-UK** [flcdrg/VsShowMissing#308]
Please add or support Visual Studio 2022

**Comment by flcdrg** [comment]
Yes, it's on my radar. Might get to it over the Christmas break.

**Comment by MikeWilliams-UK** [comment]
Thanks for your quick reply. As an open source maintainer I fully appreciate how precious your time is.

**Comment by MikeWilliams-UK** [comment]
Many thanks - It works a dream
