### ISSUE TITLE
Does not work on a solution that's just been cloned

### ISSUE THREAD

**Issue by andrewducker** [flcdrg/VsShowMissing#335]
If I clone a solution (within Visual Studio) which has some files missing, and hit "Rebuild Solution" then it builds with no errors.

If I then quit Visual Studio, and then relaunch it and the solution and again hit "Rebuild Solution" then the build fails (as I'd expect).

Waiting for all of the extensions to load doesn't make it work correctly.  Closing the solution and reopening it again doesn't make it work correctly.  I have to fully close Visual Studio and then relaunch it and *then* it notices the missing files and correctly fails the build.

Any ideas?

**Comment by flcdrg** [comment]
Nothing immediately comes to mind. Which version of Visual Studio are you using?

**Comment by flcdrg** [comment]
I've just tried to reproduce this by doing the following (admittedly I'm using the latest build in VS 2019. I'll be publishing this shortly)

1. Open Visual Studio 2019
2. Go to **Git*, then **Clone Repository**
3. For the repository, use `https://github.com/flcdrg/VsShowMissing.git` and select a new local directory
4. Wait for the clone to finish
5. In **Solution Explorer** double-click on **tests.sln**
6. Ignore any prompt to install C++ components
7. Press Ctrl-Alt-B to build solution
8. Observe expected errors in **Error List** window

If you can provide more details, then please reopen the issue, thanks.
