### ISSUE TITLE
No results with 2.6.5.98 on VS 15.8.1

### ISSUE THREAD

**Issue by TripleEmcoder** [flcdrg/VsShowMissing#51]
I see no results after building projects with missing files (missing both ways). I did try so disable the ignore list and .gitignore to make sure there's no interference, but still nothing. What could be wrong? Is there a log that I could enable to see what's going on?

**Comment by flcdrg** [comment]
Not really. I'll try it out under 15.8 myself to see if I can see any problems.

**Comment by flcdrg** [comment]
Just tested with 15.8.6 and everything seems to work ok.

There isn't really any logging at the moment for releases, but if you're willing to get your hands dirty, it shouldn't be too hard to grab the source and run it locally. There is then debug logging that could be useful.

Closing for now, but re-open if you find out any more info.
