### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ErikLevin** [flcdrg/VsShowMissing#8]
Hi, first of all thanks for a very useful extension. However, I'm having problems with memory usage. Each time something builds in my solution while ShowMissing is enabled, devenv.exe grabs a hundred MB or so of memory which it never releases, until it uses 2.8 GB. runs out, and crashes. Disabling the extension causes devenv.exe to behave normally again. Worth noting, my solution is fairly large (138 projects).

I feel like something might have happened in 2.0 because I never noticed such severe problems with running this extension until the other day. I would try to revert to 1.3 but I can't figure out how to do that... So for now I've had to disable the extension. :(

**Comment by flcdrg** [comment]
Hi @ErikLevin, thanks very much for taking the time to analyse this. That is a decent size solution - I've worked on ones like that before and they can present some challenges at the best of times!

The major change for 2.0 was the 'looking at files on disk that aren't in the project' feature. You can disable this in Tools | Options | Show Missing. Theoretically doing that should bring it pretty much back to the 1.9 behaviour.

I'm going to release an update shortly that has some code tweaks that should help a little with memory usage. I'll aim to run it under a memory profiler to do some further testing in the next few days and if I find anything there, I'll push out some more update(s).

**Comment by flcdrg** [comment]
I did the memory profiling and was pretty happy with the results after the 2.1 update. I'll close this for now unless anything new shows up.
