### ISSUE TITLE
*.vspscc Should be ignored by default

### ISSUE THREAD

**Issue by Mertsch** [flcdrg/VsShowMissing#9]
`*.vspscc` are part of how VS + TFS / VSTS does source control integration and have no value at all to the solution/project

Such file should exist for every project that is under source control with `Project.csproj.vspscc` as an example

**Comment by flcdrg** [comment]
I'll add that in to the default patterns to ignore.

**Comment by Mertsch** [comment]
@flcdrg Thanks.

While looking at your code I also noticed that you support `.gitignore` you might want to take a look at `.tfignore`, too

**Comment by flcdrg** [comment]
Yes, that makes sense. I think the format is pretty much the same

**Comment by flcdrg** [comment]
Separate issue #16 for .tfignore
