### ISSUE TITLE
2019 version missing right click include option

### ISSUE THREAD

**Issue by xand7** [flcdrg/VsShowMissing#92]
Hello,

I've encountered a small issue with the 2019 version.  When right clicking on the 'file is not included' error messages I don't seem to have the 'include in project' and 'delete file on disk' options as I had in previous versions.

Cheers,

**Comment by flcdrg** [comment]
Thanks for the report. I noticed a similar problem. Need to figure out why the menu isn't including the extra items.

**Comment by flcdrg** [comment]
Update has been published to marketplace.
